### ISSUE TITLE
No indentation

### ISSUE THREAD

**Issue by dav1312** [vBread/bd-contributions#17]
## Description
The plugin removes all indentation from the code

### Reproduction Steps
Look at code with indentation

### Screenshots
![image](https://user-images.githubusercontent.com/63931154/126865644-6d9c76bb-048a-4597-93b5-5ef88052a650.png)
![image](https://user-images.githubusercontent.com/63931154/126865651-9b9299ce-2de3-419d-88c3-d83a93fc41f8.png)

### Additional Info

- Plugin Name: BetterCodeblocks
- Discord Release: All
- Platform: Windows

**Comment by greenmancode** [comment]
I was having the same issue and figured out a solution. The plugin appears to do this on purpose because there's a function called "dedent" in the code. The solution was to jump to [Line 127](https://github.com/vBread/bd-contributions/blob/1be95b118ae78f3f46941df24c68403de9533e86/BetterCodeblocks/BetterCodeblocks.plugin.js#L127) of the plugin and comment out the line like this:
```js
// nodes[0].content = this.dedent(nodes[0].content)
```
This prevents the content of the code block from getting dedented.

**Comment by tameTNT** [comment]
@greenmancode Thank you so much! This fixed the issue for me.

**Comment by multimokia** [comment]
I have opened a pull request removing this line #21

**Comment by Mattwmaster58** [comment]
Very weird that this was added https://github.com/xiBread/bd-contributions/commit/7b91e450024c2081786329877269ecf93b0c1e72#diff-b7c8c81cf59afb891cd2b90e4da6d798888175428d33d14046177633173951d8R121

No explanation in the commit message either beyond "release 1.3.0", but the changelog says "Extraneous leading whitespace is now removed from codeblocks", so maybe that's what it was supposed to do?

**Comment by Glaived** [comment]
@xiBread ???
